### ISSUE TITLE
~~/utils/abilities.ts only works with Nuxt base directory structure

### ISSUE THREAD

**Issue by jasonhollander** [Barbapapazes/nuxt-authorization#13]
Component usage currently requires that the `/utils/abilities*` is located at the root of the client app.  In instances where `/app` contains the client side nuxt directory structure the components fail to reference the abilities.  Will be an issue with layers or non-conventional directory structures.

Workaround by keeping the utils colocated with the client side code and referencing the full path in the server imports.  ex: import {addPost} from '~~/app/utils/abilities'

Ideally the /utils folder could exist at the root.

**Comment by Barbapapazes** [comment]
Hey 👋,

Could you please provide a minimal reproduction? I'm not sure to understand the issue here 🤔

**Comment by Barbapapazes** [comment]
Or you're referring to server side import of the abilities defined in the client directory?

**Comment by jasonhollander** [comment]
Yeah, the client side only works if the utils folder is in the client root.  In my case my entire client (components, pages, ..) is in /app/* and server is at /server/*.  Currently works if i structure as:
```
/app/utils/abilities.ts
/server/*
```
but requires that I import from /server as per the above comment '~~/app/utils/abilities'

**Comment by Barbapapazes** [comment]
Hey,

This is mostly a issue within the documentation but the upcoming `shared` folder, https://github.com/nuxt/nuxt/issues/28675, will help.

For the moment, I will improve the documentation.
