### ISSUE TITLE
Documentation inconsistant with implemnation for Can/Cannot Components

### ISSUE THREAD

**Issue by madc** [Barbapapazes/nuxt-authorization#14]
The documentation describes the usage of `Can`/`Cannot` as follows:

```
<template>
  <Can
    :ability="editPost"
    :args="[post]"
  >
    <button>Edit</button>
  </Can>
</template>
```

[Looking at the implementation](https://github.com/Barbapapazes/nuxt-authorization/blob/main/src/runtime/components/Can.vue#L6), the components expect the prop to be named `:bouncer-ability="..."`.

I'll be happy to create a PR, just need to know If we want to fix implementation or documentation.

**Comment by Barbapapazes** [comment]
Hey,

This is an issue within the documentation. 👍

Could you make a PR?

**Comment by madc** [comment]
Ah, already fixed. Thanks!
