### ISSUE TITLE
Can/Cannot Components expect args-prop to be iterable.

### ISSUE THREAD

**Issue by madc** [Barbapapazes/nuxt-authorization#15]
I would expect the `args` prop to be optional, as abilities do not necessarily have them.
But the component fails with the following message if none is provided:
```
props.args is not iterable (cannot read property undefined)
```

A workaround is to provide an empty Array as `args` prop (`args="[]"`).

**Comment by Barbapapazes** [comment]
Hey,

Could you provide a reproduction? If the ability does not need args, type should be never.

https://github.com/Barbapapazes/nuxt-authorization/blob/0980005f6d5c6d27812f7bc325c54605f09966c3/src/runtime/components/Can.vue#L7

**Comment by Barbapapazes** [comment]
Yes, an empty array is needed. If you have any solution to solve this, I'll be happy to accept

**Comment by madc** [comment]
Same, already fixed. Thanks, very cool!!

**Comment by Barbapapazes** [comment]
I haven't yet release a new version but expect something today.
