### ISSUE TITLE
build export warning

### ISSUE THREAD

**Issue by jasonhollander** [Barbapapazes/nuxt-authorization#16]
Running into a rollup issue with build related to reexport of "useNitroApp"

```
WARN  Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt-authorization/dist/runtime/server/utils/bouncer.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

`NODE_VERSION=22.5.1`

**Comment by Barbapapazes** [comment]
Hello,

I don't know why there is a warning like this.

**Comment by Barbapapazes** [comment]
Ok I found this, I will investigate.

https://github.com/nuxt/nuxt/issues/25710#issuecomment-1935622896

**Comment by Barbapapazes** [comment]
I found something. I have to update the readme and make a release.

**Comment by Barbapapazes** [comment]
This, https://github.com/Barbapapazes/nuxt-authorization/commit/57345df621dd410b53f796e06a75dd5e0e8c2e5a, should resolve your issue ([v0.1.0](https://www.npmjs.com/package/nuxt-authorization/v/0.1.0))

**Comment by jasonhollander** [comment]
fantastic, seems to be resolved.  Thank you!
