### ISSUE TITLE
`Can` & `Cannot` components are not reactives

### ISSUE THREAD

**Issue by madc** [Barbapapazes/nuxt-authorization#17]
A simple usecase for this issue:
In a navigation bar we have a "Login" link. Once the user logs in, this Link is replaced with a "Profile" link.

Currently the Can/Cannot components need a complete remount of the component to update their state. In case of the navigation bar, this basically means a page refresh.Looking into the code, I think the issue is here:

https://github.com/Barbapapazes/nuxt-authorization/blob/de44df9458529d296024ebb626ca2ff53b6e662e/src/runtime/components/Can.vue#L12

A quick (untested) fix could maybe look like this:

```typescript
const can = ref<boolean>(false)

watchEffect(async () => {
  can.value = await allows(props.bouncerAbility, ...args)
})
```

**Comment by Barbapapazes** [comment]
I think that a computed could be enough for this.

Do you mind created a PR?

**Comment by madc** [comment]
`computed` is not working well with `aync` functions.

**Comment by Barbapapazes** [comment]
> `computed` is not working well with `aync` functions.

Yes, you're right!
