### ISSUE TITLE
Rename components' props?

### ISSUE THREAD

**Issue by zAlweNy26** [Barbapapazes/nuxt-authorization#24]
Probably a dumb issue, but why not rename the prop `bouncerAbility` of the `Can` and `Cannot` components, to just `ability`? It's more direct in my opinion and less verbose.

**Comment by Barbapapazes** [comment]
Hey 👋,

I love this idea since we `defineAbility`, it makes more sens to pass an ability, rather than an bouncer ability.

Do you mind to make a PR?

**Comment by zAlweNy26** [comment]
Yeah no problem, I'll do that
