### ISSUE TITLE
Nitro server cannot read '$authorization'

### ISSUE THREAD

**Issue by mercey123** [Barbapapazes/nuxt-authorization#29]
I've followed the guide to add this module. 
I can see $authorization on front-end context, however back-end gives following error: 
` ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading '$authorization')
  at allows (./node_modules/.pnpm/nuxt-authorization@0.3.0_magicast@0.3.5_rollup@4.24.0_webpack-sources@3.2.3/node_modules/nuxt-authorization/dist/runtime/server/utils/bouncer.js:5:36)  
  at Object.handler (./server/api/group/index.post.ts:10:1)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:1978:19  
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1_webpack-sources@3.2.3/node_modules/unctx/dist/index.mjs:72:16)  
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1_webpack-sources@3.2.3/node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:2270:7)`
  
  Logging the context shows this: 
  `{ allowGuest: false,
  original: [AsyncFunction (anonymous)],
  execute: [Function: execute] }`
  
  Will be glad to provide more info if necessary.

**Comment by manuel-84** [comment]
for server side I had to do this.... it's not clear from documentation

```
import { canSendEmail } from '@/utils/abilities'

export default defineEventHandler(async (event) => {
  const authorized = await allows(event, canSendEmail)
  if (!authorized) {
    throw createError({ statusCode: 403, message: 'Unauthorized' })
  }
 ...
})
```

**Comment by Barbapapazes** [comment]
Hey @manuel-84,

Could you tell me more what's not clear in the documentation?

@mercey123, could you please provide some code to help me to understand your issue?

thanks

**Comment by manuel-84** [comment]
> Hey @manuel-84,
> 
> Could you tell me more what's not clear in the documentation?
> 
> @mercey123, could you please provide some code to help me to understand your issue?
> 
> thanks

the documentation  says that you can use the same API for client and server but there are some differences and I think it would be better to have a full server api example to clearify

while on client I can just do `await allows(myAbility)`, on server i had first to import the myAbility from the utils/abilites, or I had an error "myAbility is not defined", and then pass the event to allows function: `allows(event, myAbility)` or I get the error "Cannot read properties of undefined (reading '$authorization')"

**Comment by Barbapapazes** [comment]
Hey 👋,

Ok, I see. I will update the documentation.

**Comment by Barbapapazes** [comment]
Please, tell me if there are any elements that are still unclear! 🙌
