### ISSUE TITLE
[feature request] Add template prop: `tag` to Vue components

### ISSUE THREAD

**Issue by maartenvanhunsel** [Barbapapazes/nuxt-authorization#31]
Hi @Barbapapazes, are you open to extending the Vue components with dynamic components? Personally, I prefer to avoid deeply nested HTML tags. In this regard, I would like to propose adding a new optional property: `tag`, to facilitate the creation of dynamic components and to prevent unnecessary nesting of items.

If you agree I may create a PR. Let me know.

**Comment by Barbapapazes** [comment]
Hey @maartenvanhunsel 👋,

This is a great idea but instead of using `tag`, I would prefer `as` to align with components library.

Do you mind open a PR? Thanks 🙌
