### ISSUE TITLE
[Feature request] Define multiple abilities for components

### ISSUE THREAD

**Issue by maartenvanhunsel** [Barbapapazes/nuxt-authorization#34]
It would be beneficial to have the capability to define multiple abilities. In many of our applications, parent components may encompass several actions. For instance, creating a post and updating a post.

```
<Can
    :ability="[createPost, editPost]"
    :args="[post]"
  >
    <button>Edit</button>
  </Can>
```

or with multiple args

```
<Can
    :ability="[createPost, editPost]"
    :args="[[post], [post, another-argument]]"
  >
```

**Comment by Barbapapazes** [comment]
Hey!

Don't you think it's easier to combine ability within a new ability instead of composing them like this?

**Comment by maartenvanhunsel** [comment]
While this approach may be somewhat more intricate, it provides the developer with comprehensive information through a single line of code. Additionally, we utilize capabilities somewhat differently than by creating separate abilities, as our backend supplies all user permissions via the API. 

Thus, we maintain only one ability to encompass all functionalities.

```
type PermissionTargets = 'any' | 'all';
export const laravelPermission = defineAbility((user: User, permissions: string, target: PermissionTargets = 'any'): boolean => {
    if (!permissions) {
        return true;
    }

    const _permissions = permissions.split('|');
    if (target === 'any') {
        return _permissions.some(permission => user.permissions?.includes(permission));
    } else if (target === 'all') {
        return _permissions.every(permission => user.permissions?.includes(permission));
    }

    return false;
});
```

```
<Can
    :ability="laravelPermission"
    :args="['projects.store']"
>
```

Now we need to develop custom abilities to determine whether the logged-in user is `internal` or `external`. To achieve this, I would prefer:

```
<Can
    :ability="[laravelPermission, isInternal]"
    :args="['projects.store']"
>
```

**Comment by Barbapapazes** [comment]
Ok, I see. Do you think you can open a PR for this? I have more free time so it will be faster for me to review your PR!
